spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/local-gym-tracker
    username: localuser
    password: localpassword
  jpa:
    hibernate:
      ddl-auto: create-drop

jwt:
  secret-key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa